from sqlmodel.ext.asyncio.session import AsyncSession

from app.models.db_models import Tag, Team, User


async def create_init_data(async_session_factory: type[AsyncSession]):
    async with async_session_factory() as session:
        tag_admin = Tag(name="admin")
        tag_reader = Tag(name="reader")
        tag_contributor = Tag(name="contributor")
        team_preventers = Team(
            name="Preventers",
            headquarters="Sharp Tower",
            tags=[tag_admin, tag_reader, tag_contributor],
        )
        team_z_force = Team(
            name="Z-Force",
            headquarters="Sister Margaret's Bar",
            tags=[tag_reader],
        )
        team_empty = Team(name="empty", headquarters="without users")
        session.add(team_preventers)
        session.add(team_z_force)
        session.add(team_empty)
        # commit is not a must have if the team.id generated by Python before commit.
        # await session.commit()

        user_deadpond = User(
            name="Deadpond",
            first_name="Dive",
            last_name="Wilson",
            # team_id=team_z_force.id,
            team=team_z_force,
        )
        user_a = User(
            name="a",
            first_name="b",
            last_name="c",
            # team_id=team_z_force.id,
            team=team_z_force,
        )
        user_rusty_man = User(
            name="Rusty-Man",
            first_name="Tommy",
            last_name="Sharp",
            # team_id=team_preventers.id,
            team=team_preventers,
        )
        user_spider_boy = User(
            name="Spider-Boy",
            first_name="Pedro",
            last_name="Parqueador",
        )
        session.add(user_deadpond)
        session.add(user_a)
        session.add(user_rusty_man)
        session.add(user_spider_boy)
        await session.commit()
