name: ci
run-name: ${{ github.workflow}} by @${{ github.actor }} ${{ github.event.pull_request.head.sha }}

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}-pr${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  ci_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use public pip index only for ci demo
        run: echo "https://pypi.org/simple" > PIP_INDEX_URL.secret

      - name: create env file from secret.CI_ENV
        run: |
          echo "${{ secrets.CI_ENV }}" > .env
          echo "============== echo secrets.CI_ENV"
          echo "${{ secrets.CI_ENV }}"
          echo "============== cat .env"
          cat .env
          wc -l .env

      - name: Install deps
        run: |
          python --version
          make ci-install
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run lint
        run: |
          export LOGFIRE_SEND_TO_LOGFIRE=false
          export SKIP=pyright,pytest
          make lint

      # https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md
      - uses: jakebailey/pyright-action@v2

  ci_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use public pip index only for ci demo
        run: echo "https://pypi.org/simple" > PIP_INDEX_URL.secret

      - name: create env file from secret.CI_ENV
        run: |
          echo "${{ secrets.CI_ENV }}" > .env
          echo "============== echo secrets.CI_ENV"
          echo "${{ secrets.CI_ENV }}"
          echo "============== cat .env"
          cat .env
          wc -l .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run the Docker images
        run: make run-docker-compose

      - name: Install deps
        run: |
          python --version
          make ci-install
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run tests
        # above `make lint` includes pytest with default options
        run: |
          export LOGFIRE_SEND_TO_LOGFIRE=false
          make test

      - name: Upload results to Codecov
        if: ${{ strategy.job-index == 0 }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Stop containers
        if: always()
        run: docker-compose down

  ci_all_green:
    if: always()
    needs:
      - ci_lint
      - ci_test
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
